
const REQUEST_GET_PD = 'REQUEST_GET_PD';
const REQUEST_GET_PD_SUCCESS = 'REQUEST_GET_PD_SUCCESS';
const REQUEST_GET_PD_FAILED = 'REQUEST_GET_PD_FAILED';

const REQUEST_GET_PD_DETAIL = 'REQUEST_GET_PD_DETAIL';
const REQUEST_GET_PD_DETAIL_SUCCESS = 'REQUEST_GET_PD_DETAIL_SUCCESS';
const REQUEST_GET_PD_DETAIL_FAILED = 'REQUEST_GET_PD_DETAIL_FAILED';

const REQUEST_DELETE_PD = 'REQUEST_DELETE_PD';
const REQUEST_DELETE_PD_SUCCESS = 'REQUEST_DELETE_PD_SUCCESS';
const REQUEST_DELETE_PD_FAILED = 'REQUEST_DELETE_PD_FAILED';

const REQUEST_UPDATE_PD = 'REQUEST_UPDATE_PD';
const REQUEST_UPDATE_PD_SUCCESS = 'REQUEST_UPDATE_PD_SUCCESS';
const REQUEST_UPDATE_PD_FAILED = 'REQUEST_UPDATE_PD_FAILED';

const REQUEST_SEARCH_PD = 'REQUEST_SEARCH_PD';
const REQUEST_SEARCH_PD_SUCCESS = 'REQUEST_SEARCH_PD_SUCCESS';
const REQUEST_SEARCH_PD_FAILED = 'REQUEST_SEARCH_PD_FAILED';

const REQUEST_ADD_PD = 'REQUEST_ADD_PD';
const REQUEST_ADD_PD_SUCCESS = 'REQUEST_ADD_PD_SUCCESS';
const REQUEST_ADD_PD_FAILED = 'REQUEST_ADD_PD_FAILED';

const REQUEST_GET_PD_BY_CATE = 'REQUEST_GET_PD_BY_CATE';
const REQUEST_GET_PD_BY_CATE_SUCCESS = 'REQUEST_GET_PD_BY_CATE_SUCCESS';
const REQUEST_GET_PD_BY_CATE_FAILED = 'REQUEST_GET_PD_BY_CATE_FAILED';

const REQUEST_FILTER_PD = 'REQUEST_FILTER_PD';
const REQUEST_FILTER_PD_SUCCESS = 'REQUEST_FILTER_PD_SUCCESS';
const REQUEST_FILTER_PD_FAILED = 'REQUEST_FILTER_PD_FAILED';

//

const REQUEST_GET_CATE = 'REQUEST_GET_CATE';
const REQUEST_GET_CATE_SUCCESS = 'REQUEST_GET_CATE_SUCCESS';
const REQUEST_GET_CATE_FAILED = 'REQUEST_GET_CATE_FAILED';

const REQUEST_GET_CATE_DETAIL = 'REQUEST_GET_CATE_DETAIL';
const REQUEST_GET_CATE_DETAIL_SUCCESS = 'REQUEST_GET_CATE_DETAIL_SUCCESS';
const REQUEST_GET_CATE_DETAIL_FAILED = 'REQUEST_GET_CATE_DETAIL_FAILED';

const REQUEST_ADD_CATE = 'REQUEST_ADD_CATE';
const REQUEST_ADD_CATE_SUCCESS = 'REQUEST_ADD_CATE_SUCCESS';
const REQUEST_ADD_CATE_FAILED = 'REQUEST_ADD_CATE_FAILED';

const REQUEST_UPDATE_CATE = 'REQUEST_UPDATE_CATE';
const REQUEST_UPDATE_CATE_SUCCESS = 'REQUEST_UPDATE_CATE_SUCCESS';
const REQUEST_UPDATE_CATE_FAILED = 'REQUEST_UPDATE_CATE_FAILED';

const REQUEST_DELETE_CATE = 'REQUEST_DELETE_CATE';
const REQUEST_DELETE_CATE_SUCCESS = 'REQUEST_DELETE_CATE_SUCCESS';
const REQUEST_DELETE_CATE_FAILED = 'REQUEST_DELETE_CATE_FAILED';

//

const REQUEST_LOGIN = 'REQUEST_LOGIN';
const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

//

const REQUEST_GET_POST = 'REQUEST_GET_POST';
const REQUEST_GET_POST_SUCCESS = 'REQUEST_GET_POST_SUCCESS';
const REQUEST_GET_POST_FAILED = 'REQUEST_GET_POST_FAILED';

const REQUEST_GET_DETAIL_POST = 'REQUEST_GET_DETAIL_POST';
const REQUEST_GET_DETAIL_POST_SUCCESS = 'REQUEST_GET_DETAIL_POST_SUCCESS';
const REQUEST_GET_DETAIL_POST_FAILED = 'REQUEST_GET_DETAIL_POST_FAILED';

const REQUEST_ADD_POST = 'REQUEST_ADD_POST';
const REQUEST_ADD_POST_SUCCESS = 'REQUEST_ADD_POST_SUCCESS';
const REQUEST_ADD_POST_FAILED = 'REQUEST_ADD_POST_FAILED';

const REQUEST_EDIT_POST = 'REQUEST_EDIT_POST';
const REQUEST_EDIT_POST_SUCCESS = 'REQUEST_EDIT_POST_SUCCESS';
const REQUEST_EDIT_POST_FAILED = 'REQUEST_EDIT_POST_FAILED';

const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
const REQUEST_DELETE_POST_SUCCESS = 'REQUEST_DELETE_POST_SUCCESS';
const REQUEST_DELETE_POST_FAILED = 'REQUEST_DELETE_POST_FAILED';

//
const REQUEST_SET_CART = 'REQUEST_SET_CART';
const REQUEST_SET_CART_SUCCESS = 'REQUEST_SET_CART_SUCCESS';
const REQUEST_SET_CART_FAILED = 'REQUEST_SET_CART_FAILED';

const REQUEST_GET_CART = 'REQUEST_GET_CART';
const REQUEST_GET_CART_SUCCESS = 'REQUEST_GET_CART_SUCCESS';
const REQUEST_GET_CART_FAILED = 'REQUEST_GET_CART_FAILED';

const REQUEST_ADD_CART = 'REQUEST_ADD_CART';
const REQUEST_ADD_CART_SUCCESS = 'REQUEST_ADD_CART_SUCCESS';
const REQUEST_ADD_CART_FAILED = 'REQUEST_ADD_CART_FAILED';

const REQUEST_EDIT_CART = 'REQUEST_EDIT_CART';
const REQUEST_EDIT_CART_SUCCESS = 'REQUEST_EDIT_CART_SUCCESS';
const REQUEST_EDIT_CART_FAILED = 'REQUEST_EDIT_CART_FAILED';

const REQUEST_DELETE_CART = 'REQUEST_DELETE_CART';
const REQUEST_DELETE_CART_SUCCESS = 'REQUEST_DELETE_CART_SUCCESS';
const REQUEST_DELETE_CART_FAILED = 'REQUEST_DELETE_CART_FAILED';

const REQUEST_DELETE_CART_ALL = 'REQUEST_DELETE_CART_ALL';
const REQUEST_DELETE_CART_ALL_SUCCESS = 'REQUEST_DELETE_CART_ALL_SUCCESS';
const REQUEST_DELETE_CART_ALL_FAILED = 'REQUEST_DELETE_CART_ALL_FAILED';

const REQUEST_UP_CART = 'REQUEST_UP_CART';
const REQUEST_UP_CART_SUCCESS = 'REQUEST_UP_CART_SUCCESS';
const REQUEST_UP_CART_FAILED = 'REQUEST_UP_CART_FAILED';

const REQUEST_DOWN_CART = 'REQUEST_DOWN_CART';
const REQUEST_DOWN_CART_SUCCESS = 'REQUEST_DOWN_CART_SUCCESS';
const REQUEST_DOWN_CART_FAILED = 'REQUEST_DOWN_CART_FAILED';

export default {

  REQUEST_FILTER_PD,
  REQUEST_FILTER_PD_SUCCESS,
  REQUEST_FILTER_PD_FAILED,
  
  REQUEST_UP_CART,
  REQUEST_UP_CART_SUCCESS,
  REQUEST_UP_CART_FAILED,

  REQUEST_DOWN_CART,
  REQUEST_DOWN_CART_SUCCESS,
  REQUEST_DOWN_CART_FAILED,

  REQUEST_DELETE_CART_ALL,
  REQUEST_DELETE_CART_ALL_SUCCESS,
  REQUEST_DELETE_CART_ALL_FAILED,

  REQUEST_GET_CART,
  REQUEST_GET_CART_SUCCESS,
  REQUEST_GET_CART_FAILED,

  REQUEST_SET_CART,
  REQUEST_SET_CART_SUCCESS,
  REQUEST_SET_CART_FAILED,

  REQUEST_ADD_CART,
  REQUEST_ADD_CART_SUCCESS,
  REQUEST_ADD_CART_FAILED,

  REQUEST_EDIT_CART,
  REQUEST_EDIT_CART_SUCCESS,
  REQUEST_EDIT_CART_FAILED,

  REQUEST_DELETE_CART,
  REQUEST_DELETE_CART_SUCCESS,
  REQUEST_DELETE_CART_FAILED,

  REQUEST_LOGIN,
  REQUEST_LOGIN_SUCCESS,
  REQUEST_LOGIN_FAILED,

  REQUEST_GET_PD,
  REQUEST_GET_PD_SUCCESS,
  REQUEST_GET_PD_FAILED,

  REQUEST_GET_PD_DETAIL,
  REQUEST_GET_PD_DETAIL_SUCCESS,
  REQUEST_GET_PD_DETAIL_FAILED,

  REQUEST_DELETE_PD,
  REQUEST_DELETE_PD_SUCCESS,
  REQUEST_DELETE_PD_FAILED,

  REQUEST_UPDATE_PD,
  REQUEST_UPDATE_PD_SUCCESS,
  REQUEST_UPDATE_PD_FAILED,

  REQUEST_ADD_PD,
  REQUEST_ADD_PD_SUCCESS,
  REQUEST_ADD_PD_FAILED,

  REQUEST_SEARCH_PD,
  REQUEST_SEARCH_PD_SUCCESS,
  REQUEST_SEARCH_PD_FAILED,

  REQUEST_GET_PD_BY_CATE,
  REQUEST_GET_PD_BY_CATE_SUCCESS,
  REQUEST_GET_PD_BY_CATE_FAILED,

  //

  REQUEST_GET_CATE,
  REQUEST_GET_CATE_SUCCESS,
  REQUEST_GET_CATE_FAILED,

  REQUEST_GET_CATE_DETAIL,
  REQUEST_GET_CATE_DETAIL_SUCCESS,
  REQUEST_GET_CATE_DETAIL_FAILED,

  REQUEST_ADD_CATE,
  REQUEST_ADD_CATE_SUCCESS,
  REQUEST_ADD_CATE_FAILED,

  REQUEST_UPDATE_CATE,
  REQUEST_UPDATE_CATE_SUCCESS,
  REQUEST_UPDATE_CATE_FAILED,

  REQUEST_DELETE_CATE,
  REQUEST_DELETE_CATE_SUCCESS,
  REQUEST_DELETE_CATE_FAILED,

  //
  REQUEST_GET_POST,
  REQUEST_GET_POST_SUCCESS,
  REQUEST_GET_POST_FAILED,

  REQUEST_GET_DETAIL_POST,
  REQUEST_GET_DETAIL_POST_SUCCESS,
  REQUEST_GET_DETAIL_POST_FAILED,

  REQUEST_ADD_POST,
  REQUEST_ADD_POST_SUCCESS,
  REQUEST_ADD_POST_FAILED,

  REQUEST_EDIT_POST,
  REQUEST_EDIT_POST_SUCCESS,
  REQUEST_EDIT_POST_FAILED,

  REQUEST_EDIT_POST,
  REQUEST_EDIT_POST_SUCCESS,
  REQUEST_EDIT_POST_FAILED,

  REQUEST_DELETE_POST,
  REQUEST_DELETE_POST_SUCCESS,
  REQUEST_DELETE_POST_FAILED,
}